// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc3925.OmniDrive.commands;

import com.sun.squawk.util.MathUtils;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3925.OmniDrive.Robot;

/**
 *
 */
public class  Drive extends Command {

    public Drive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.omniDriveSubsystem);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
    
    private double[] omniDrive(double movement, double strafe, double spin)
    {
        double[] speeds = new double[4];
        
        movement = trimInput(movement);
        strafe = trimInput(strafe);
        spin = trimInput(spin);
        
        Vector basevec = Vector.vectorXY(strafe, movement);
        
        //create speeds from basevec
     
        
        //adjust the speeds based on rotation
        
        return speeds;
    }
    
    private double trimInput(double in)
    {
        if (in > 1.0d) in = 1.0d;
        if (in < -1.0d) in = -1.0d;
        return in;
    }
    
    private static class Vector {
        
        public double angle;
        public double r;
        
        public Vector (double r, double angle)
        {
            this.r = r;
            this.angle = angle;
        }
        
        public static Vector vectorXY(double x, double y)
        {
            return new Vector(Math.sqrt(x*x + y*y),MathUtils.atan2(y, x));
        }
        
        public Vector add(Vector v)
        {
            double r, a, x, y;
            
            x = this.xdisplacement() + v.xdisplacement();
            y = this.ydisplacement() + v.ydisplacement();
            
            return vectorXY(x,y);
        }
        
        public double xdisplacement()
        {
            return r*Math.cos(angle);
        }
        public double ydisplacement()
        {
            return r*Math.sin(angle);
        }
    }
}
